// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB8RaDOkhFSMUkaU11ZnvbS4fWjeDU2gw',
    appId: '1:154568266701:web:ceb39f827125e1beddaa84',
    messagingSenderId: '154568266701',
    projectId: 'pauseflow-e95a7',
    authDomain: 'pauseflow-e95a7.firebaseapp.com',
    storageBucket: 'pauseflow-e95a7.firebasestorage.app',
    measurementId: 'G-E4MKSMMNGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2b3xUSnoqH_dhtxIGKBejZXKWYyW-blM',
    appId: '1:154568266701:android:baa097384c4df9c4ddaa84',
    messagingSenderId: '154568266701',
    projectId: 'pauseflow-e95a7',
    storageBucket: 'pauseflow-e95a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtYbd-iEUH4tkO61avKiqX2Nlrm-uJ44o',
    appId: '1:154568266701:ios:bc434538ef628a88ddaa84',
    messagingSenderId: '154568266701',
    projectId: 'pauseflow-e95a7',
    storageBucket: 'pauseflow-e95a7.firebasestorage.app',
    iosBundleId: 'com.example.breatheApp',
  );
}
